name: Z64 - YouTube upload

on:
  workflow_dispatch:

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: CristobalPenaloza/z64packer-yt-upload@v1
        with:
          yt_client_secrets: ${{ secrets.YOUTUBE_CLIENT_SECRETS }}
          yt_request_token: ${{ secrets.YOUTUBE_REQUEST_TOKEN }}
          background_image: "https://cdn.wikimg.net/en/zeldawiki/images/thumb/a/af/MM_Japas's_Room.png/1200px-MM_Japas's_Room.png"
